# Generated by Django 4.0.4 on 2022-05-02 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Familiares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='fechaDeNacimiento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
